services:
  - type: web
    name: akkreditatsiya-dashboard
    runtime: node
    plan: free
    buildCommand: "echo ok"
    startCommand: "node server.js"
    healthCheckPath: /healthz
    envVars:
      - key: PUSH_TOKEN
        generateValue: true
      - key: SEED_URL
        value: https://new.atmu.uz/
      - key: DEADLINE
        value: "2026-09-28T23:59:00+05:00"
